version: '3.1'

services:
#Настройки самой базы данных
  db:
    image: postgres:12-alpine
    restart: always
    environment:
        POSTGRES_USER: test
        POSTGRES_PASSWORD: test
    volumes:
        - ./db:/var/lib/postgresql/data
#Для удобного просмотра в браузере
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    links:
      - db