---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: ClusterIP
  selector:
    app: postgresql
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: inner-stage
spec:
  ports:
    - name: web
      port: 80
      protocol: TCP
    - name: api
      port: 9000
      protocol: TCP
  selector:
    app: web-service
  type: ClusterIP
