---
  - name: Install Java
    hosts: elasticsearch
    tasks:
      - name: Set facts for Java 11 vars
        set_fact:
          java_home: "/opt/jdk/{{ java_jdk_version }}"
        tags: java
      - name: Upload .tar.gz file containing binaries from local storage
        copy:
          mode: 0644
          src: "{{ java_oracle_jdk_package }}"
          dest: "/tmp/jdk-{{ java_jdk_version }}.tar.gz"
        register: download_java_binaries
        until: download_java_binaries is succeeded
        tags: java
      - name: Create folder java home
        become: true
        file:
            path: "{{ java_home }}"
            state: directory
      - name: Ensure installation dir exists
        become: true
        file:
          mode: 0644
          state: directory
          path: "{{ java_home }}"
        tags: java
      - name: Extract java in the installation directory
        become: true
        unarchive:
          mode: 0644
          copy: false
          src: "/tmp/jdk-{{ java_jdk_version }}.tar.gz"
          dest: "{{ java_home }}"
          extra_opts: [--strip-components=1]
          creates: "{{ java_home }}/bin/java"
        tags:
          - skip_ansible_lint
          - java
      - name: Export environment variables
        become: true
        template:
          mode: 0644
          src: jdk.sh.j2
          dest: /etc/profile.d/jdk.sh
        tags: java
        
  - name: Install Elasticsearch
    hosts: elasticsearch
    tasks:
      - name: Copy package Elasticsearch
        copy:
          mode: 0644
          src: "{{ elastic_package }}"
          dest: "/tmp/{{ elastic_package }}"
        register: copy_elastic
        tags: elasticsearch
      - name: Create directrory for Elasticsearch
        become: true
        file:
          mode: 0644
          state: directory
          path: "{{ elastic_home }}"
        tags: elasticsearch
      - name: Create folder for Elasticsearch
        become: true
        file:
            path: "{{ elastic_home }}"
            state: directory
      - name: Extract Elasticsearch in the installation directory
        become: true
        unarchive:
          mode: 0644
          copy: false
          src: "/tmp/elasticsearch-{{ elastic_version }}-linux-x86_64.tar.gz"
          dest: "{{ elastic_home }}"
          extra_opts: [--strip-components=1]
          creates: "{{ elastic_home }}/bin/elasticsearch"
        tags:
          - elastic
      - name: Set environment Elastic
        become: yes
        template:
          mode: 0644
          src: templates/elk.sh.j2
          dest: /etc/profile.d/elk.sh
        tags: elastic
        
  - name: Install Kibana
    hosts: kibana
    tasks:
      - debug:
            msg: "https://artifacts.elastic.co/downloads/kibana/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
      - name: Upload tar.gz Kibana from remote URL
        get_url:
          url: "https://artifacts.elastic.co/downloads/kibana/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
          dest: "/tmp/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
          mode: 0755
          timeout: 60
          force: true
        tags: kibana
      - name: Create dirrectory fo kibana
        become: true
        file:
          mode: 0644
          state: directory
          path: "{{ kibana_home }}"
        tags: kibana
      - name: Extract Kibana in the installation directory
        become: true
        unarchive:
          mode: 0644
          copy: false
          src: "/tmp/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
          dest: "{{ kibana_home }}"
          creates: "{{ kibana_home }}/bin/kibana"
        tags:
          - skip_ansible_lint
          - kibana
      - name: Set environment Kibana
        become: yes
        template:
          mode: 0644
          src: templates/kibana.sh.j2
          dest: /etc/profile.d/kibana.sh
        tags: elastic